### PR TITLE
WIP: Unite set_vals implementations

### LINKED ISSUE #45: The set_vals method is implemented five times in the tests
The `set_vals` method that is responsible for initialising an overlay in the tests is implemented five times. All these implementations are very similar. We can save a lot of code if we can just implement this method twice.

### PR DESCRIPTION
**Pull request by Solomon1732**
United the `set_vals` implementations under one class. This is to avoid code reduplication.

This is very much a WIP, and feedback for how to structure the code is desired.

Fixes #45

### CODE REVIEW

**Comment by Solomon1732** [comment]
This seems to be the failure. What does it mean? 😅 Aside for #52 local tests pass without issues.
```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    coverage[toml] from https://files.pythonhosted.org/packages/e4/6a/fa167da3ac886b4777bfe37a86a2d664637dff12837dd6187ce9cdd5eb70/coverage-5.3-cp38-cp38-manylinux1_x86_64.whl#sha256=0f313707cdecd5cd3e217fc68c78a960b616604b559e9ea60cc16795c4304259
Session tests failed.
Ran multiple sessions:
* black: failed
* tests: failed
Error: Process completed with exit code 1.
```

**Comment by devos50** [comment]
@Solomon1732 Looking at it, see #55

**Comment by devos50** [comment]
Please rebase this PR on the latest commit on the `master` branch 👍

**Comment by Solomon1732** [comment]
I did not unite the functions under one class since "if a fixture is defined inside a class, it can only be requested by tests inside that class." Trying to unite them under one class resulted in the fixtures not being visible to the test functions, or indeed, to `poetry run pytest --fixtures`.
https://docs.pytest.org/en/stable/fixture.html#fixture-availabiility

I also did not add `init_nodes` as optional parameters since they are apparently not yet a feature in pytest.

**Comment by Solomon1732** [comment]
Closing pull request since I messed up the history. I'll open a new one

**Pull request closed without merging**
